# Generated by Django 3.0.5 on 2020-05-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0002_auto_20200503_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='u_pass',
            field=models.CharField(max_length=15),
        ),
    ]
