# Generated by Django 3.0.5 on 2020-05-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0005_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='u_name',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
