# Generated by Django 3.0.5 on 2020-05-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0006_auto_20200505_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Data',
        ),
    ]
