# Generated by Django 3.0.5 on 2020-05-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0008_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Data',
        ),
    ]
